### ISSUE TITLE
GitHub PR release labeler bot

### ISSUE THREAD

**Issue by imjasonh** [imjasonh/ideas#80]
Label merged PRs with the minimum version release containing that change. E.g., "this change is in release v0.2.3+"

Might be complicated when there are rollbacks, but an owner can remove or update the label if it’s wrong.

**Comment by michael-todorovic** [comment]
Not a label but Semantic-release is actually able to post in the PR with a plugin https://github.com/pmowrer/semantic-release-github-pr
The result is at https://github.com/renovatebot/renovate/pull/11565#issuecomment-961903110

**Comment by imjasonh** [comment]
Cool! Figured something like this existed. Thanks
