### ISSUE TITLE
AirPods walkie talkies

### ISSUE THREAD

**Issue by imjasonh** [imjasonh/ideas#96]
Both AirPods have a mic and a speaker. It might be possible to have two people each use one and have some app pipe the input from one into the output of the other, and vice versa. Sort of like a very short-range walkie talkie.

I have no idea if both inputs are available to apps, or if when you put the second one in an ear it disables one of the mics.

I also have no idea what this would be useful, but it could be fun.

**Comment by mattmoor** [comment]
I've wanted exactly this, although there isn't a particularly great range.  If it could be used in a crowded space with noise cancelling, then shut up and take my money.

**Comment by imjasonh** [comment]
Well this isn't encouraging:

![125CDD8B-A984-44D6-BE48-8B76232B3593](https://user-images.githubusercontent.com/210737/138453220-17bde178-d7db-484a-9762-253e48682a0a.jpeg)

"The active AirPod microphone" definitely sounds like only one mic works at a time, and it's probably not going to switch based on which one's talking. 😕
